project:
  type: website

website:
  title: "Sonja D. Winter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
    tools:
      - icon: twitter
        href: https://www.twitter.com/winterstat
      - icon: github
        href: https://www.github.com/winterstat
  back-to-top-navigation: true
  page-footer: "Copyright 2023, Sonja D. Winter"
  twitter-card: true
  open-graph: true


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

