---
title: "Publications"
format: 
  html:
    toc: true
    toc-location: right
    link-external-newwindow: true
---

Bonifay W., Winter, S. D., Skoblow, H., & Watts. A. (revise & resubmit). Good fit is not a Sufficient Indicator of Replication Success. \[Invited contribution to special issue of *Assessment* on "Assessment, Measurement, and Registered Replication."\]

Depaoli, S., Winter, S. D., & Liu, H. (revise & resubmit). Under-Fitting and Over-Fitting: The Performance of Bayesian Model Selection and Fit Indices in SEM. *Structural Equation Modeling: A Multidisciplinary Journal.*

Merkle, E., Ariyo, O., Garnier-Villarreal, M., & Winter, S. D. (revise & resubmit). [Opaque Prior Distributions in Bayesian SEM](https://arxiv.org/abs/2301.08667). *Methodology.*

Parmenter, J. G. & Winter, S. D. (in press). Inequity within the LGBTQ+ Community as a Distal Stressor: An Extension of Minority Stress Theory. *Psychology of Sexual Orientation and Gender Diversity.*

## 2022 - 2023

Winter, S. D., & Depaoli, S. (2023). Illustrating the Value of Prior Predictive Checking for Bayesian Structural Equation Modeling. *Structural Equation Modeling: A Multidisciplinary Journal.* doi:[10.1080/10705511.2022.2164286](https://doi.org/10.1080/10705511.2022.2164286) \[[OSF](https://osf.io/3tq6c/)\]

Winter, S. D., & Depaoli, S. (2022). Detecting Prior-Data Disagreement in Bayesian Structural Equation Modeling. *Structural Equation Modeling: A Multidisciplinary Journal.* doi:[10.1080/10705511.2022.2039066](https://doi.org/10.1080/10705511.2022.2039066) \[[OSF](https://osf.io/u3p7h/)\]

Winter, S. D., & Depaoli, S. (2022). Sensitivity of Bayesian Model Fit Indices to the Prior Specification of Latent Growth Models. *Structural Equation Modeling: A Multidisciplinary Journal, 29*(5), 667-686. doi:[10.1080/10705511.2022.2032078](https://www.doi.org/10.1080/10705511.2022.2032078) \[[OSF](https://osf.io/zd3uh/)\]

Winter, S. D., & Depaoli, S. (2022). Performance of Model Fit and Selection Indices for Bayesian Structural Equation Modeling with Missing Data. *Structural Equation Modeling: A Multidisciplinary Journal, 29*(4), 531-549. doi:[10.1080/10705511.2021.2018656](https://doi.org/10.1080/10705511.2021.2018656) \[[OSF](https://osf.io/xf8hw/)\]

## 2020 - 2021

van de Schoot, R., Winter, S. D., Griffioen, E., Grimmelikhuijsen, S., Arts, I., Veen, D., Grand- field, E. M., & Tummers, L. G. (2021). The Use of Questionable Research Practices to Survive in Academia: Expert Elicitation, Prior-Data Conflicts, Bayes Factors for Replication Effects, and the Bayes Truth Serum. *Frontiers in Psychology: Quantitative Psychology & Measurement, 12*, 621547 doi:[10.3389/fpsyg.2021.621547](https://doi.org/10.3389/fpsyg.2021.621547) \[[OSF](https://osf.io/raqsd/)\]

Arroyo, A. C., Winter, S. D., Depaoli, S., & Zawadzki, M. J. (2021). Illuminating Differences in The Psychological Predictors of Academic Performance for First- And Continuing-Generation Students. *Journal of Educational and Psychological Research, 3*(2), 234-246.

Depaoli, S., Winter, S. D., & Visser, M. (2020). The Importance of Prior Sensitivity Analysis in Bayesian Statistics: Demonstrations using an Interactive Shiny App. *Frontiers in Psychology: Quantitative Psychology & Measurement, 11*, 3271. doi:[10.3389/fpsyg.2020.608045](https://doi.org/10.3389/fpsyg.2020.608045) \[[OSF](https://osf.io/eyd4r/)\]

Smid, S. C., & Winter, S. D. (2020). Dangers of the Defaults: A Tutorial on the Impact of Default Priors when using Bayesian SEM with Small Samples. *Frontiers in Psychology: Quantitative Psychology & Measurement, 11*, 611963. doi:[10.3389/fpsyg.2020.611963](https://doi.org/10.3389/fpsyg.2020.611963) \[[OSF](https://osf.io/m6byv/)\]

Winter, S. D., & Depaoli, S. (2020). An Illustration of Bayesian Approximate Measurement Invariance with Longitudinal Data and a Small Sample Size. *International Journal of Behavioral Development, 44*(4), 371-382. doi:[10.1177/0165025419880610](https://doi.org/10.1177/0165025419880610)

## 2018 - 2019

Depaoli, S., Winter, S. D., Lai, K., & Guerra-Peña, K. (2019). Implementing continuous non-normal skewed distributions in latent growth mixture modeling: An assessment of specification errors and class enumeration. *Multivariate Behavioral Research, 54*(6), 795-821. doi:[10.1080/00273171.2019.1593813](https://doi.org/10.1080/00273171.2019.1593813)

Hoorn, J. F., & Winter, S. D. (2018). Here comes the bad news: Doctor robot taking over. *International Journal of Social Robotics, 10*, 519-535. doi:[10.1007/s12369-017-0455-2](https://doi.org/10.1007/s12369-017-0455-2)

Tiemensma, J., Depaoli, S., Winter, S. D., Felt, J. M., Rus, H., & Arroyo, A. C. (2018). The Performance of the IES-R for Latinos and non-Latinos: Assessing Measurement Invariance. *PLoS ONE, 13*(4), e0195229. doi:[10.1371/journal.pone.0195229](https://doi.org/10.1371/journal.pone.0195229)

van de Schoot, R., Sijbrandij, M., Depaoli, S., Winter, S. D., & van Loey, N. (2018). Bayesian PTSD-Trajectory Analysis with Informed Priors Based on a Systematic Literature Search and Expert Elicitation. *Multivariate Behavioral Research, 53*(2), 267-291. doi:[10.1080/00273171.2017.1412293](https://doi.org/10.1371/journal.pone.0195229) \[[OSF](https://osf.io/vk4be/)\]

Winter, S. D., Depaoli, S., & Tiemensma, J. (2018). Assessing differences in how the CushingQoL is interpreted across countries: Comparing patients from the U.S. and the Netherlands. *Frontiers in Endocrinology, 9*, 368.doi:[10.3389/fendo.2018.00368](https://doi.org/10.3389/fendo.2018.00368)

## Pre-2018

van de Schoot, R., Sijbrandij, M., Winter, S. D., Depaoli, S., & Vermunt, J. K. (2017). The GRoLTS- Checklist: Guidelines for reporting on latent trajectory studies. *Structural Equation Modeling: A Multidisciplinary Journal, 24*(3), 451-467. doi:[10.1080/10705511.2016.1247646](https://www.doi.org/10.1080/10705511.2016.1247646) \[[OSF](https://osf.io/vw3t7/)\]

van de Schoot, R., Winter, S. D., Ryan, O., Zondervan-Zwijnenburg, M. & Depaoli, S. (2017). A systematic review of Bayesian articles in psychology: The last 25 years. *Psychological Methods, 22*(2), 217-239. doi:[10.1037/met0000100](https://doi.org/10.1037/met0000100)

Konijn, E. A., van der Schoot, R., Winter, S. D., & Ferguson, C. J. (2015). Possible solution to publication bias through Bayesian statistics, including proper null hypothesis testing. *Communication Methods and Measures, 9*(4), 280-302. doi:[10.1080/19312458.2015.1096332](https://doi.org/10.1080/19312458.2015.1096332)

## Book Chapters

Depaoli, S., Kaplan, D., & Winter, S. D. (2023). Foundations and extensions in Bayesian structural equation modeling. In Hoyle, R. (2nd Ed.) *Handbook of structural equation modeling.* New York, NY: The Guilford Press. \[[OSF](https://osf.io/24xyv/)\]

van de Schoot, R., Griffioen, E., & Winter, S. D. (2021). Dealing with imperfect elicitation results. In Hanea, A.M., Nane, G.F., Bedford, T., French, S. (Eds.), *Expert Judgment in Risk and Decision Analysis.* Basel: Springer International Publishing. \[[OSF](https://osf.io/bq28j/)\]

van de Schoot, R., Veen, D., Smeets, L., Winter, S. D., & Depaoli, S. (2020). A Tutorial on Using The Wambs Checklist to Avoid The Misuse of Bayesian Statistics. In R. van de Schoot & M. Mio ̆cević (Eds.),*Small Sample Size Solutions: A guide for applied researchers and practitioners* (pp. 30--49). London: Routledge. doi:10.4324/9780429273872-4
